plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'java-library'
    id 'eclipse'
    id 'idea'
}

version = "${mod_version}"
group = "${mod_group_id}"

base {
    archivesName = mod_id
}

loom {
    accessWidenerPath = file("src/main/resources/colony.accesswidener")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(java_version as int)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-networking-api-v1:${fabric_version}"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
